apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starlight-save-file-component
  namespace: starlight-save-file-component
spec:
  secretName: starlight-save-file-component
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "starlight-save-file-component.trueberryless.org"
