apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starlight-save-file-component
  namespace: starlight-save-file-component
spec:
  rules:
    - host: starlight-save-file-component.trueberryless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: starlight-save-file-component
                port:
                  number: 80

  tls:
    - hosts:
        - starlight-save-file-component.trueberryless.org
      secretName: starlight-save-file-component
